name: Docker Image CI

on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-image.yml'
env:
  IMAGE_NAME: opensumi/opensumi-web
  TZ: Asia/Shanghai
  REGISTRY: ghcr.io
jobs: 
  push-ghcr:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64 ]
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Login to Alibaba Cloud Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1


#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#        with:
#          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build && Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.arch }}
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/dkyy/opensumi:${{ matrix.language }}
          cache-from: type=gha
          cache-to: type=gha
